insert into customers (firstName, lastName, email, address, phone_number) values ('Mirabel', 'Skiplorne', 'mskiplorne0@telegraph.co.uk', '1 Marquette Way', '3306353074');
insert into customers (firstName, lastName, email, address, phone_number) values ('Martainn', 'Prescote', 'mprescote1@1688.com', '7 Vermont Court', '8523396570');
insert into customers (firstName, lastName, email, address, phone_number) values ('Othilia', 'Wathell', 'owathell2@vimeo.com', '6 Monument Road', '8416151147');
insert into customers (firstName, lastName, email, address, phone_number) values ('Rosalia', 'Santry', 'rsantry3@reverbnation.com', '67569 Glacier Hill Drive', '1955210588');
insert into customers (firstName, lastName, email, address, phone_number) values ('Maurice', 'Lusgdin', 'mlusgdin4@mozilla.com', '8 Bellgrove Court', '3695673386');
insert into customers (firstName, lastName, email, address, phone_number) values ('Maia', 'Ondrusek', 'mondrusek5@hugedomains.com', '30 Brickson Park Hill', '4029521571');
insert into customers (firstName, lastName, email, address, phone_number) values ('Marris', 'Bickardike', 'mbickardike6@about.me', '6 Northport Junction', '5978438996');
insert into customers (firstName, lastName, email, address, phone_number) values ('Rochell', 'Heyward', 'rheyward7@toplist.cz', '07800 Becker Hill', '3974220737');
insert into customers (firstName, lastName, email, address, phone_number) values ('Karlotta', 'McGurgan', 'kmcgurgan8@taobao.com', '6629 La Follette Alley', '2379762966');
insert into customers (firstName, lastName, email, address, phone_number) values ('Zonnya', 'Chupin', 'zchupin9@symantec.com', '63453 Bowman Crossing', '9722952652');
insert into customers (firstName, lastName, email, address, phone_number) values ('Carlyn', 'Brimilcome', 'cbrimilcomea@sourceforge.net', '825 Hansons Center', '6419293072');
insert into customers (firstName, lastName, email, address, phone_number) values ('Anselm', 'Stains', 'astainsb@geocities.jp', '5 Toban Lane', '1266447254');
insert into customers (firstName, lastName, email, address, phone_number) values ('Fairlie', 'Beckley', 'fbeckleyc@seattletimes.com', '03356 Bartelt Trail', '6085820195');
insert into customers (firstName, lastName, email, address, phone_number) values ('Aurelie', 'Toyne', 'atoyned@is.gd', '407 Lakewood Place', '3575239044');
insert into customers (firstName, lastName, email, address, phone_number) values ('Tracie', 'Portinari', 'tportinarie@ca.gov', '0738 Algoma Pass', '1905360054');
insert into customers (firstName, lastName, email, address, phone_number) values ('Dalston', 'Le - Count', 'dlecountf@hatena.ne.jp', '2 Anhalt Drive', '1613239776');
insert into customers (firstName, lastName, email, address, phone_number) values ('Maighdiln', 'True', 'mtrueg@mashable.com', '95 Surrey Alley', '5973835253');
insert into customers (firstName, lastName, email, address, phone_number) values ('Wini', 'Hubbins', 'whubbinsh@mozilla.com', '071 Anzinger Junction', '2592029626');
insert into customers (firstName, lastName, email, address, phone_number) values ('Jeremie', 'Danielsen', 'jdanielseni@seattletimes.com', '2548 Hallows Hill', '6616733113');
insert into customers (firstName, lastName, email, address, phone_number) values ('Anderson', 'Lanchberry', 'alanchberryj@163.com', '6 Truax Pass', '2068263064');
insert into customers (firstName, lastName, email, address, phone_number) values ('Web', 'd'' Elboux', 'wdelbouxk@instagram.com', '56414 Vahlen Parkway', '5123466527');
insert into customers (firstName, lastName, email, address, phone_number) values ('Avril', 'Hilliam', 'ahilliaml@addtoany.com', '84749 Sloan Circle', '2587775104');
insert into customers (firstName, lastName, email, address, phone_number) values ('Grantley', 'Schonfeld', 'gschonfeldm@auda.org.au', '099 Stone Corner Center', '1533192169');
insert into customers (firstName, lastName, email, address, phone_number) values ('Clementina', 'Giovannilli', 'cgiovannillin@wordpress.com', '54522 Cody Parkway', '1771442149');
insert into customers (firstName, lastName, email, address, phone_number) values ('Phelia', 'Culwen', 'pculweno@gmpg.org', '37274 Shopko Way', '8971257602');
insert into customers (firstName, lastName, email, address, phone_number) values ('Valenka', 'Cotesford', 'vcotesfordp@house.gov', '2 Hudson Court', '3871986409');
insert into customers (firstName, lastName, email, address, phone_number) values ('Chariot', 'Ianetti', 'cianettiq@ehow.com', '1002 Oak Drive', '2594082412');
insert into customers (firstName, lastName, email, address, phone_number) values ('Fabiano', 'Scolts', 'fscoltsr@nsw.gov.au', '23318 Ronald Regan Place', '6609855695');
insert into customers (firstName, lastName, email, address, phone_number) values ('Peri', 'Blaisdell', 'pblaisdells@tmall.com', '44754 Arapahoe Terrace', '6251773465');
insert into customers (firstName, lastName, email, address, phone_number) values ('Ted', 'Windrum', 'twindrumt@oaic.gov.au', '574 Gulseth Circle', '4063618564');
