insert into products (ean, name, price, department, family, subfamily) values('3663602814290', 'Clé à cliquet Magnusson - 7 pièces', 31.50, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148515886065', 'Clé plate Facom - 7 pièces', 39.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148515665509', 'Canif clé 6 pans Facom - 7 pièces', 24.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814559', 'Clé mixte Magnusson 20 mm', 5.60, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814306', 'Clé à double cliquet Magnusson - 2 pièces', 24.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602706427', 'Coffret tournevis à cliquet Magnusson', 24.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814566', 'Clé mixte Magnusson 21 mm', 6.10, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814399', 'Clé mixte Magnusson 7 mm', 2.10, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148515886119', 'Jeu de 5 clés à pipe débouchée Facom', 44.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602522812', 'Coffret à douilles Magnusson - 28 pièces', 39.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814573', 'Clé mixte Magnusson 23 mm', 7.50, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814269', 'Clé polygonale double Magnusson - 4 pièces', 14.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814290', 'Clé à cliquet Magnusson - 7 pièces', 31.50, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148515886065', 'Clé plate Facom - 7 pièces', 39.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148515665509', 'Canif clé 6 pans Facom - 7 pièces', 24.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814559', 'Clé mixte Magnusson 20 mm', 5.60, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814306', 'Clé à double cliquet Magnusson - 2 pièces', 24.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602706427', 'Coffret tournevis à cliquet Magnusson', 24.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814566', 'Clé mixte Magnusson 21 mm', 6.10, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814399', 'Clé mixte Magnusson 7 mm', 2.10, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148515886119', 'Jeu de 5 clés à pipe débouchée Facom', 44.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602522812', 'Coffret à douilles Magnusson - 28 pièces', 39.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814573', 'Clé mixte Magnusson 23 mm', 7.50, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814405', 'Clé mixte Magnusson 8 mm', 2.20, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602820444', 'Clé 6 pans pliante Magnusson - 8 pièces', 8.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814702', 'Clé plate Magnusson 25 x 28 mm', 7.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814894', 'Clé à molette Magnusson 12", 37 mm', 15.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814412', 'Clé mixte Magnusson 9 mm', 2.30, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602813736', 'Douille standard Magnusson 1/2" - 8 pièces', 29.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602820468', 'Clé 6 pans à tête sphérique Magnusson - 9 pièces', 9.50, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814108', 'Clé à pipe standard Magnusson 1/2" 7 mm', 3.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814023', 'Clé à pipe standard Magnusson 1/2" 8 mm', 4.10, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148515886461', 'Clé à tête sphérique Facom - 9 pièces', 29.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814986', 'Barre à poignée en T Magnusson 1/2"', 9.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814665', 'Clé plate Magnusson 18 x 19 mm', 4.60, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814719', 'Clé plate Magnusson 30 x 32 mm', 9.60, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814597', 'Clé mixte Magnusson 32 mm', 11.95, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602813545', 'Douille simple standard Magnusson 1/2" 26 mm', 3.80, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602813712', 'Douille standard Magnusson 1/2" - 14 pièces', 29.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814054', 'Clé à pipe standard Magnusson 1/2" 13 mm', 5.30, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814962', 'Adaptateur de cardan universel Magnusson 1/2"', 4.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814641', 'Clé plate Magnusson 14 x 15 mm', 3.10, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148519234381', 'Clé à cliquet 1/2" Facom', 45.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148515659799', 'Clé mixte Facom 19 mm', 13.45, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602813699', 'Douille héxagonale Magnusson 3/8" - 8 pièces', 9.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814030', 'Clé à pipe standard Magnusson 1/2" 10 mm', 4.80, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814153', 'Clé à pipe standard Magnusson 1/2" 16 mm', 7.10, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602813675', 'Douille standard Magnusson 3/8" - 40 pièces', 34.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814528', 'Clé mixte Magnusson 22 mm', 6.80, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814672', 'Clé plate Magnusson 20 x 22 mm', 5.30, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602813415', 'Douille simple standard Magnusson 1/2" 8 mm', 2.30, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3662424092367', 'Clé à molette à réglage rapide Facom 8"', 24.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602813484', 'Douille simple standard Magnusson 1/2" 17 mm', 2.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3148518372909', 'Coffret à douilles Facom - 38 pièces', 139.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814603', 'Clé plate Magnusson 6 x 7 mm', 1.95, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814481', 'Clé mixte Magnusson 16 mm', 4.40, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602813927', 'Clé dynamométrique Magnusson 1/4"', 39.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814917', 'Clé à molette Magnusson 6", 8" et 10" - 3 pièces', 24.90, 'outillage', 'outillage-a-main', 'cle-et-douille');
insert into products (ean, name, price, department, family, subfamily) values('3663602814436', 'Clé mixte Magnusson 11 mm', 2.80, 'outillage', 'outillage-a-main', 'cle-et-douille');
